minio:
  ipaddr: ${MINIO_SERVER_IP}
  username: ${MINIO_USERNAME}
  password: ${MINIO_PASSWORD}

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/minioupload?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

server:
  port: 8080
  address: 0.0.0.0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  # 设置jwt签名加密时使用的秘钥（至少256位/32字节）
  admin-secret-key: itcast-minio-jwt-secret-key-2024
  # 设置jwt过期时间
  admin-ttl: 20000
  # 设置前端传递过来的令牌名称
  admin-token-name: token
  user-secret-key: itheima-minio-jwt-secret-key-2024
  user-ttl: 20000
  user-token-name: authentication